### ISSUE TITLE
Min and Max

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#122]
We have `Min` and `Max` invokables as part of a Foldable abstraction.

But there is no corresponding generic `min` and `max` generic functions.

This is because `min` and `max` functions already exists in F# core and they return the min (or max) between two parameters.

So, we need to think how to publish these two functions, some alternatives:

 1. Add a module, something like `Foldable.Min` or `Generic.Min`
 2. Come up with a slightly different name, something like `gmin` or `minElement`

Any thoughts?

**Comment by wallymathieu** [comment]
You could use the full words as seen on [wikipedia](https://en.wikipedia.org/wiki/Maxima_and_minima). Another nice thing to have in a base library is to have the be able to get the maxima and minima (i.e. all of the matching).
