### ISSUE TITLE
Maxima, Minima

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FSharpPlus#124]
### Description

I've found that it can be useful to be able to get the set of all entities in a collection that are considered maximum or minimum given a criteria.

### Suggestion

Add maxima and minima as functions for the collections abstraction

#### minima

To take a note from an existing implementations
minima : ( 'a -> 'a -> int) -> 'a collection -> 'a collection 

 This function finds the minima in of values, preserving the sequence of retained values from the supplied collection.

It returns all those values in the supplied foldable for which there is no smaller element in the foldable.

#### minimaBy

To take a note from an existing implementation
minimaBy : ( 'a -> 'b) -> 'a collection -> 'a collection when 'b : comparison 

 This function finds the minima in of values, preserving the sequence of retained values from the supplied foldable.

It returns all those values in the supplied foldable for which there is no smaller element in the collection.

### Changes in RFC

 - Changed to collection instead of foldable.

**Comment by wallymathieu** [comment]
This is loosely connected to https://github.com/fsprojects/FSharpPlus/issues/122

**Comment by gusty** [comment]
I would define extension methods and generic functions.
If we agree that the generic signature will be `'F<'T>->('T->'T->int)->'F<'T>` then we're taking about collections rather than just foldables, see https://github.com/fsprojects/FSharpPlus/issues/116

**Comment by wallymathieu** [comment]
I think that it would make sense to restrict them.

**Comment by wallymathieu** [comment]
Something like:
```
    let maxima l=
        let sorted = List.sortDescending l
        match sorted with
        | []|[_] -> sorted
        | max::_ -> List.takeWhile ((compare max) >> (=) 0) sorted
    let minima l=
        let sorted = List.sort l
        match sorted with
        | []|[_] -> sorted
        | min::_ -> List.takeWhile ((compare min) >> (=) 0) sorted

    let maximaBy projection l=
        let sorted = List.sortByDescending projection l
        match sorted with
        | []|[_] -> sorted
        | max::_ -> List.takeWhile ((compare <| projection max) >> (=) 0 << projection) sorted
    let minimaBy projection l=
        let sorted = List.sortBy projection l
        match sorted with
        | []|[_] -> sorted
        | min::_ -> List.takeWhile ((compare <| projection min) >> (=) 0 << projection) sorted
```

**Comment by gusty** [comment]
You can go ahead and create a PR.
You can add it initially as an extension for `List`.
If you want you can include also the extensions for other collections.
And if you still want to code further, you can include the generic versions ;)

**Comment by wallymathieu** [comment]
I've tried to add an implementation in the same style as other similar collection implementations

**Comment by wallymathieu** [comment]
Since these are not common operations (among programmers), perhaps better to only add the generic functions that make it easier to implement them.
