### ISSUE TITLE
Applicative Documentation Typo

### ISSUE THREAD

**Issue by DylanLukes** [fsprojects/FSharpPlus#151]
I'm omitting the standard issue template, as this is a rather straightforward documentation issue:

The docs list the signature of Applicative's ap (<*>) operator as:

```fsharp
static member (<*>) (f:'T->'U, x:Applicative<'T>) : Applicative<'U>
```

But this is incorrect, it should be:

```fsharp
static member (<*>) (f:Applicative<'T->'U>, x:Applicative<'T>) : Applicative<'U>
```

**Comment by gusty** [comment]
Thanks for pointing that.

Do you want to submit a fix ?

PS: No worries for the standard issue template, is just a guideline for us.
