### ISSUE TITLE
CI should produce nupkgs as artifacts

### ISSUE THREAD

**Issue by TOTBWF** [fsprojects/FSharpPlus#170]
Right now, it is rather tricky to depend on HEAD using paket, as you need to invoke `build.sh`. I propose that the CI should produce a `.nupkg`.

As an aside, it appears that the `NuGet` fake target is borked.

**Comment by TOTBWF** [comment]
Digging a bit deeper, it appears that the root cause of the `pack` breakage is https://github.com/fsprojects/Paket/issues/3540, so we may have to upgrade paket

**Comment by gusty** [comment]
Or drop it and use plain nuget instead.

**Comment by TOTBWF** [comment]
Oddly enough, `paket pack` works just fine for me, it's `msbuild` that is screwing up

**Comment by wallymathieu** [comment]
Should be easier now to update paket. Specified versions of paket are found here:
https://github.com/fsprojects/FSharpPlus/blob/master/build.cmd#L2
https://github.com/fsprojects/FSharpPlus/blob/master/build.sh#L29-L31

**Comment by TOTBWF** [comment]
After smashing my head against this for a few hours, I'm starting to think it would just be better to put out a new release. Thoughts?

**Comment by gusty** [comment]
Yes, let's do that !

**Comment by gusty** [comment]
The new release is out: https://www.nuget.org/packages/FSharpPlus/1.1.0-CI00271
