### ISSUE TITLE
Documentation generation fails on Appveyor

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FSharpPlus#176]
### Description

Getting error while trying to build documentation on AppVeyor and Windows

### Repro steps

Run a documentation target using FAKE

### Actual behavior

```
error FS0192: internal error: convMethodRef: could not bind to method
```
See pull request build output for full logs: https://github.com/fsprojects/FSharpPlus/pull/173

### Known workarounds

Documentation seems to build fine on Travis

### Related information 

* Operating system : Windows
* Branch : master

### Potential solution

Migrate doc generation to use later Nuget packages in order to avoid mismatched DLL.

Easiest way to migrate docs to new nuget packages is probably to use https://github.com/jet/XRay/blob/master/docsrc/tools/doclib.fsx
since it means fewer local code changes compared to migrate to FAKE5.

**Comment by wallymathieu** [comment]
Perhaps some inspiration can be found from https://github.com/fsprojects/FSharp.Text.RegexProvider/pull/31 ?

**Comment by gusty** [comment]
That would also free us to use paket / FAKE.
