### ISSUE TITLE
Need more detail on "List functor" special case explanation

### ISSUE THREAD

**Issue by zanedp** [fsprojects/FSharpPlus#204]
Note: the following is not mandatory, just a guideline. Feel free to describe your bug report or suggestion in another way.

### Description

On https://fsprojects.github.io/FSharpPlus/applicative-functors.html, the sentence "You can think of the List functor as a particular case of a function `f: Naturals -> 't`" needs additional explanation. After explaining that a functor is essentially something that can be mapped over, that sentence does not follow the previous simple explanation. What does that sentence mean?

**Comment by gusty** [comment]
Thanks for your feedback.

I did that specific file for a user group talk I did some years ago. Forgive me if it’s confusing, but it was to show an intuitive way to understand that functions are also “mappables” as lists are. It’s normally easy to understand that concept for lists, but for functions sometimes is not that obvious.

Maybe we can remove that sentence from the docs, as it's confusing without enough context.
