### ISSUE TITLE
Is there an operator for ">> map"?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#210]
Consider the following code to create a domain type with validation:

```f#
let create =
    String.trim
    >> notEmpty
    >=> maxLength 10
    >> map CustomerNumber
```

Is there an operator I can use to replace `>> map`? I haven't been able to find any. It would make things more "symmetrical"/consistent.

To be clear, this would be similar to how `>=>` is an operator for `>> bind`.

**Comment by cannorin** [comment]
There is no known operator for `Functor f => (f a -> f b) -> (b -> c) -> (f a -> f c)` or `Functor f => (b -> c) -> (f a -> f b) -> (f a -> f c)` in the literature (read: Hoogle).

**Comment by cmeeren** [comment]
Thanks!

**Comment by honza77** [comment]
in my quest for understanding point-less  (poit-free of course) i've created one:

let inline (>>>) f g = f >> (map g)
