### ISSUE TITLE
Function to "collapse" a bifunctor to an arbitrary type?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#212]
I'm looking for a function that I can use to "collapse" a bifunctor to an arbitrary type. For example, for `Result`:

```f#
let someName f g = function
  | Ok x -> f x
  | Error x -> g x
```

It seems like this might be a standard concept, but I haven't found anything in the docs. I might have missed something, though. Does such a function exist in FSharpPlus?

**Comment by gusty** [comment]
What about this?

https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Operators.fs#L36

**Comment by cmeeren** [comment]
Thanks! Exactly what I needed.
