### ISSUE TITLE
Make 'either' generic over all bifunctors?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#213]
I have no strong background in CT; sorry if this makes no sense.

I notice that `either` is restricted to the `Result` type. Wouldn't it make more sense to make it generic over all bifunctors? E.g. `Choice<_,_>`.

I don't actually need this, I just noticed it and felt like asking.

**Comment by gusty** [comment]
Yes, they all should be made `Bifoldable`, then `bifold` would be your function ;)

See https://hackage.haskell.org/package/bifunctors-5.4.1/docs/Data-Bifoldable.html

**Comment by cmeeren** [comment]
Makes sense. :) Should `either` be deprecated, then?

**Comment by gusty** [comment]
Yes, deprecated and/or moved as an extension for `Result`.
