### ISSUE TITLE
How to implement filter for custom type?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#216]
I have a custom type `Skippable<'a>` that's just like `Option` (but semantically different). It's defined in a [separate library](https://github.com/cmeeren/FSharp.JsonSkippable/).

In my code, I want to extend this type to support `filter`. With that in mind, I have tried the following, but none of them work (I have also tried switching the arguments):

```f#
type Skippable<'a> with
  static member Filter(s, p) = Skippable.filter p s
```

```f#
type Skippable<'a> with
  member this.Filter(p) = Skippable.filter p this
```

```f#
type FSharpPlus.Control.Filter with
  static member Filter(s, p) = Skippable.filter p s
```

In all cases, when I try to use `filter` on a `Skippable<_>` value, I get a compiler error saying

> No overloads match for method 'ToSeq'.

Is this because I am using extension members? Is it possible to add support to custom types using extension members?

**Comment by cannorin** [comment]
F#+ currently does not support orphan instances i.e. does not allow type class instantiation if neither

1. the instance is defined along with the type class itself (e.g. built-in with F$+), nor
2. the instance is defined along with the target type (in your case, inside the FSharp.JsonSkippable)

This is a restriction coming from the F# compiler. However, https://github.com/dotnet/fsharp/pull/6805 would enable us to define orphan instances.

**Comment by cmeeren** [comment]
I see, thanks for the clarification.
