### ISSUE TITLE
Valid composition fails with 'type constraint mismatch'

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#217]
Below, `f1` and `f2` gives two parts of a composition/transformation. `f3a` composes `f1` and `f2` and compiles. However, `f3b` composes the actual code in `f1` and `f2`, and does not compile:

> FS0071 Type constraint mismatch when applying the default type 'obj' for a type inference variable. No overloads match for method 'Sequence'. The available overloads are shown below. Consider adding further type constraints

```f#
type Role = Role
module Role =
  let create (str: string) : Async<Result<Role, string>> =
    failwith ""


let (f1: string list -> Async<Result<Role, string> list>) =
  traverse Role.create

let (f2: Async<Result<Role, string> list> -> Async<Result<Role list, string>>) =
  map sequence

let (f3a: string list -> Async<Result<Role list, string>>) =
  f1 >> f2

let (f3b: string list -> Async<Result<Role list, string>>) =
  traverse Role.create >> map sequence
```

Note that if you loosen the return type annotation of `Role.create` (e.g. `Async<Result<Role, _>>`), it compiles. Is also compiles if you use an explicit `Async.map` implementation instead of the generic `map`.

**Comment by cmeeren** [comment]
Hang on, something else is weird here.

**Comment by cmeeren** [comment]
Fixed the repro.

**Comment by gusty** [comment]
This looks clearly like an F# bug.

I'm not sure whether there is a way to workaround it from inside the library, I will think about it.

For sure, the best workaround in client code is to make it a bit less generic:

    let (f3b: string list -> Async<Result<Role list, string>>) =
      traverse Role.create >> Async.map sequence
