### ISSUE TITLE
upcoming BCL will bring overloads, and likely break building the lib

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharpPlus#221]
Using Rider's FSI, having this in a script:
```fsharp
#load "src/FSharpPlus/Internals.fs"
#load "src/FSharpPlus/Extensions.fs"
#load "src/FSharpPlus/Converter.fs"
```

I'm getting:

> src\FSharpPlus\Converter.fs(84,72): error FS0041: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Decimal.TryParse(s: ReadOnlySpan<char>, style: NumberStyles, provider: IFormatProvider, result: byref<decimal>) : bool, Decimal.TryParse(s: string, style: NumberStyles, provider: IFormatProvider, result: byref<decimal>) : bool

Reason being that Decimal.TryParse is having new overloads in recent BCL updates (can't find it yet in the online documentation).

The fix will be to add type annotations:

```fsharp
    static member TryParse (_: decimal       , _: TryParse) = fun x -> Decimal.TryParse (x, NumberStyles.Any, CultureInfo.InvariantCulture) |> tupleToOption : option<decimal>
```
into 
```fsharp
    static member TryParse (_: decimal       , _: TryParse) = fun (x: string) -> Decimal.TryParse (x, NumberStyles.Any, CultureInfo.InvariantCulture) |> tupleToOption : option<decimal>
``` 

see `(x : string)` in the lambda, to fix the type and allow the compiler to pick the right `Decimal.TryParse` overload.

**Comment by gusty** [comment]
Would it really break user code or is it going to break our compilation?
My wild guess is that x is solved as string and once compiled it will stay like that.
In your repro you are compiling the lib as you are referencing the sources.
Anyway we'll have to fix it at some point.

**Comment by smoothdeveloper** [comment]
It will break building the library, and it is not something specific to F#+, nor F# language.

See C# examples of the concept: https://blogs.msdn.microsoft.com/ericlippert/2012/01/09/every-public-change-is-a-breaking-change/

In F#, the addition of overloads will force addition of type annotations in places where new overload avoids the compiler resolving the specific one.

**Comment by gusty** [comment]
I guess  768693c7 solves this issue.

Otherwise please re-open
