### ISSUE TITLE
Unused samples folder

### ISSUE THREAD

**Issue by CameronAavik** [fsprojects/FSharpPlus#226]
When I was first looking in this repo for samples I stumbled upon this folder:
https://github.com/fsprojects/FSharpPlus/tree/master/src/FSharpPlus.Samples

But it contains no samples and so I thought that maybe there were plans to write some samples but they weren't started.

I only just realised now a month or so later when reading the readme that there are samples in this folder:
https://github.com/fsprojects/FSharpPlus/tree/master/src/FSharpPlus/Samples

I know the readme points to the second one, but perhaps the first folder should be removed if it is not being used?

**Comment by wallymathieu** [comment]
The samples folder contains a fsproj project referencing fsx files in `src/FSharpPlus/Samples`
You could move the samples from `src/FSharpPlus/Samples` to `src/FSharpPlus.Samples` in order to compile them only when compiling the samples project.

**Comment by wallymathieu** [comment]
Note these lines: https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus.Samples/FSharpPlus.Samples.fsproj#L12-L18

**Comment by gusty** [comment]
Maybe we can place a txt file advising to look for the samples in the proper folders.

In any case, I personally would like to deprecate them and move somehow all valuable samples to either tests or docs.

**Comment by wallymathieu** [comment]
Yes, would be nicer to have some of it rendered as docs.
