### ISSUE TITLE
Rename liftA2 to lift2

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#234]
I think `liftA2` is here for historical reasons: we used to have `lift2M` as well.

I don't think we need to keep calling it `liftA2`, we can rename it to `lift2` and deprecate the old name.

**Comment by MNie** [comment]
@gusty I think we could close this one since pr was merged ;)

**Comment by gusty** [comment]
Sure, thanks for the reminder.

Closed as per #234
