### ISSUE TITLE
Rename optional function?

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#256]
The generic function `optional` doesn't work.
It has been defined before the `<|>` operator.

We can fix it it easily, but this shows that so far nobody used it.

So I was thinking that this might be a 2nd chance to consider it.

I think it provides some value, it's very popular in parser combinators, but I noticed that in F# world it landed more as `opt` than `optional`, FParsec is probably the reason why.

Should we take this opportunity to rename it? Is there really evidence that it's been called `opt` in F#?

**Comment by wallymathieu** [comment]
`optional` gives more weight compared to `opt`. A quick search through github for for opt and optional seems to indicate that opt is used more for configuration options (perhaps influenced by c# usage).

**Comment by wallymathieu** [comment]
I.e. it's not clear.

**Comment by gusty** [comment]
tbh I found only two examples: fparsec and f#-for-fun-and-profit parsers (which seems to be heavy influenced by fparsec).

I couldn't find more, but that means those two are very important references at the moment.

Another advantage is that someone reading the docs but using F# 1.0 could get confused as `optional` doesn't work there.

**Comment by wallymathieu** [comment]
Sounds like a good reason to me to rename it to `opt`.
