### ISSUE TITLE
Improve usability of NonEmptyList

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#259]
I'm willing to improve usability of `NonEmptyList` as it's a very interesting type to use, but right now provides some complicated ways of constructing it which defeats the purpose.

Right now, the easiest way to create a `NonEmptyList` is be using the `NonEmptyList.create` function:

    NonEmptyList.create 1 [2;3;4;5;6]

I propose:

 - Create a computation expression (now that yield is implicit) to easy and intuitive creation:
```
    type NelBuilder () =
      member _.Zero () = failwith "It should never reach here."
      member _.Combine (a: NonEmptyList<'T>, b) = a ++ b
      member _.Yield  x = NonEmptyList.singleton x
      member _.Delay expr = expr () :  'NonEmptyList


let nel = NelBuilder ()

// Usage 
> let x = nel {1; 2; 3; 4; 5; 6} ;;
val x : NonEmptyList<int> = { Head = 1
                                  Tail = [2; 3; 4; 5; 6] }
```
A good thing is that we'll get some guarantees since `nel {}` is a compiler error.
```
> let x = nel {} ;;

  let x = nel {} ;;
  --------^^^

stdin(5,9): error FS0003: This value is not a function and cannot be applied.
```

Unfortunately range expressions won't work, maybe there's a way to defining the but implies redefining the `..` (range) operators which I would prefer to avoid as we don't want F#+ to be so invasive. But ...

 - Add a `range` function, similar to `Enumerable.Range`:

```
> NonEmptyList.range 1 6 ;;
val it : NonEmptyList<int> = { Head = 1
                               Tail = [2; 3; 4; 5; 6] }
```

 - An interesting use of semigroups like NonEmptyList is to be able to use a variant of `choice` which doesn't require an `empty` member, which would make it accessible to Either-like types.

```
choice [Error "Parser failed"; Ok 42; Ok 21] ;;

  choice [Error "Parser failed"; Ok 42; Ok 21] ;;
  ----------------------------------^^

stdin(5,35): error FS0001: No overloads match for method 'Empty'. The available overloads are shown below.
```

We can create a specific version for `NonEmptyList`:

```
> NonEmptyList.choice (nel {Error "Parser failed"; Ok 42; Ok 21}) ;;
[<Struct>]
val it : Result<int,string> = Ok 42
```

Also the `reduce` function becomes a safe one in `NonEmptyList`, we should add it.

 - Allow a conversion from potentially empty collections:

This is a backdoor to the safety `NonEmptyList` provides, but sometimes we use APIs that work with lists, although they fail at runtime when the list is empty. We can convert to these collections, the problem arise when converting back. So we can add to `NonEmptyList`something like:

```
module Unchecked =
    let toNonEmpty s =
        match Seq.toList s with
        | []    -> invalidArg "s" "Sequence is empty"
        | x::xs -> NonEmptyList.create x xs
```
which will allow us to convert from but forcing us to acknowledge the Unsafe operation:

```
> let x = [1;2;3;4] // coming from API
> NonEmptyList.reduce (+) (Unchecked.toNonEmpty x) ;;
val it : int = 10
```

 - Shorten the name to `NonEmpty`

This will probably be for v2.0 still we can do a dirty duplication of the module and a type alias to avoid a breaking change.

**Comment by adz** [comment]
I'd like to request `NonEmptyList.ofList` that returns an Option, with None if empty.

I mean if you're using this type, you're buying into safety -- so safer conversion should be well supported. If I want to make sure I'm dealing with possible empty list, I'd have to do this currently:

```
match myUnknownList with
| hd::tail -> Some <| NonEmptyList.create hd tail
| _ -> None
```

or something like that... 

Also, I have no problem with "NonEmptyList" as the type name, and think it's probably better... unless you plan to support generic "NonEmpty" on multiple collection types?

**Comment by gusty** [comment]
> I'd like to request NonEmptyList.ofList that returns an Option, with None if empty.

I was about to add that function some years ago, I just didn't find a good name.
`ofList` already as a generic counterpart with a different signature, maybe something like `tryOfList`.

> I mean if you're using this type, you're buying into safety 
Yes, that's the whole point. In addition, it's a container that is a semigroup so it has relaxed constraints, which makes possible some operations.

> Also, I have no problem with "NonEmptyList" as the type name, and think it's probably better... unless you plan to support generic "NonEmpty" on multiple collection types?

I find it a bit long to type. In Haskell they use NonEmpty, but it's true that in Haskell `list` is a main collection, as opposed to F# where we have almost equally distributed seq/array/list

**Comment by gusty** [comment]
@adz What about `NList` ?

So we can add in the future an `NSeq`.

**Comment by adz** [comment]
I believe it's not used common enough to warrant an abbreviation. That's my
opinion...

Looking at other examples, Elm and Scala cats have fully written out
NonEmptyList.

Haskell had NonEmpty but is positioned in Data.List so has context.

I could get used to NList if you feel strongly, but personally think it's
cryptic without benefit.

**Comment by adz** [comment]
Also seems R has NList for named lists, python has a multidimensional list
lib called NList, and could also be construed as numeric list.

**Comment by gusty** [comment]
Well, the difference is that in F# you normally call [module].[function] like `Seq.map` that's why you don't want to have a long name at least in the module.

**Comment by adz** [comment]
Point taken!

I was wondering if it's common to do things like `module NList = NonEmptyList`
