### ISSUE TITLE
API docs give 404 for the source-code links of functions

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/FSharpPlus#273]
Take, for instance, this page: https://fsprojects.github.io/FSharpPlus/reference/fsharpplus-string.html. Each link to the source code (to the right of the brief description) shows a 404 error.

Since the description is rarely enough to understand what a function does, the links are helpful, provided that they work ;). The alternative being to try to find the source code by hand. Not too hard, but quite time consuming.

**Comment by gusty** [comment]
That's probably because since the last time the API docs were generated (from my branch) the structure of the project changed.

I have to re-generate the API docs and deploy again.

Or finish my branch ;)

**Comment by gusty** [comment]
The new build branch is merged.
Doc site is updated, so links should work now

**Comment by abelbraaksma** [comment]
@gusty thanks! Just checked, works indeed. Will close this then ;)
