### ISSUE TITLE
Add support for custom monadic interfaces like IEffect<out T>

### ISSUE THREAD

**Issue by oncicaradupopovici** [fsprojects/FSharpPlus#285]
I have a monadic data structure written in a c# library and exposed as an interface like IEffect<out T>. I use this monad in a F# project. I need a way to mark my data structure as a member of functor/monad type classes in order to use polymorphic fns  like map , bind, etc...

One ideea is to access them through instance members.

**Comment by wallymathieu** [comment]
You could add the static members (on your c# classes) expected by f#+ in order to use map et.c. See the documentation around specific [abstractions](http://fsprojects.github.io/FSharpPlus/abstractions.html).

**Comment by oncicaradupopovici** [comment]
The public api written in c# exposes an interface not a class. 
I cannot add static members on interfaces.

**Comment by oncicaradupopovici** [comment]
Think about IObservable<'T>
You have added support out of the box, but if it was my abstraction I would have had no way to extend it to work with your type classes.

**Comment by gusty** [comment]
I think this will work once the update in the compiler being tested in https://github.com/fsprojects/FSharpPlus/issues/261 is released.

In the meanwhile we can add more fallback overloads to an instance member implementation.

Which abstractions are you interested in, specifically for that interface?

**Comment by oncicaradupopovici** [comment]
For my use-case I need Functor Applicative and Monad.
Thank you!

**Comment by gusty** [comment]
I see a problem for `>>=' since its implementation doesn't have extra parameters.

Is upgrading your interface to an abstract class a possibility?

**Comment by oncicaradupopovici** [comment]
I have managed to work around this issue by wrapping the C# interface in a single case union and added static methods on that. 


type Effect<'T> = Effect of IEffect<'T>
.....

type Effect<'T> with
    static member Map (x, f) = Effect.map  f x
    static member Return (x) = Effect.return' x
    static member (>>=) (x,f) = Effect.bind f x
    static member (<*>) (f,x) = Effect.apply f x

While this will do for now, I think there should be a way to provide "type class instances" for interfaces and also for types that I don't own.

Thank you very much for your great support!

**Comment by gusty** [comment]
We could add some sort of support dor interfaces to some operations but not to all of them. 

I think the new feature above mentioned for visibility on extensions will address both: interfaces and types you don’t own.
