### ISSUE TITLE
RC version missing files for Fable

### ISSUE THREAD

**Issue by Shmew** [fsprojects/FSharpPlus#294]
in the latest stable release there are no directories in the fsproj. With the changes to putting files into directories, the fsproj needs to be updated so that Fable can properly compile the project.

Currently this is the output when trying to build the project:
![image](https://user-images.githubusercontent.com/11186595/76709877-74fa1a80-66d0-11ea-800a-9a6f4a54c526.png)

Which results in:
![image](https://user-images.githubusercontent.com/11186595/76709889-9824ca00-66d0-11ea-85f7-f193a8ecc356.png)

The fix should be pretty simple, just expand the [fsproj](https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/FSharpPlus.fsproj#L101) to be:

```xml
  <!-- Add source files to "fable" folder in Nuget package - required for the library to be consumable by Fable -->
  <ItemGroup>
    <Content Include="*.fsproj; *.fs" PackagePath="fable/" />
    <Content Include="Extensions/*.fs" PackagePath="fable/FSharpPlus/Extensions" />
    <Content Include="Control/*.fs" PackagePath="fable/FSharpPlus/Control" />
    <Content Include="Math/*.fs" PackagePath="fable/FSharpPlus/Math" />
    <Content Include="Data/*.fs" PackagePath="fable/FSharpPlus/Data" />
  </ItemGroup>
```

**Comment by wallymathieu** [comment]
Perhaps you'd want to make a small PR to fix it @Shmew ?

**Comment by gusty** [comment]
I wonder how can we prevent this to happen with out Fable CI / tests?

**Comment by Shmew** [comment]
You'd have to parse the fsproj and see if the globbing patterns cover all of your fs files in your project I think. 

It's probably easier to just make fable-splitter a dotnet-cli dependency for the fable tests and try to split the project using it.

**Comment by gusty** [comment]
@Shmew  RC4 is published 
It would be great if you could give it a try and let us know how it goes.

**Comment by Shmew** [comment]
@gusty it is indeed working now!
