### ISSUE TITLE
RC4 - DList isn't fully Fable compatible

### ISSUE THREAD

**Issue by Shmew** [fsprojects/FSharpPlus#307]
Fable isn't able to type test generic arguments, so [this line](https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Data/DList.fs#L40) when compiled via Fable gives a warning that it isn't valid.

**Comment by gusty** [comment]
Yes, I saw that.

But I am not sure how typically you define equality in Fable. Do you know how?

**Comment by Shmew** [comment]
I've always just worked around it in the past, I played around in the repl for a while with no success. I'm not sure if it's possible for this type of scenario?

Maybe @MangelMaxime or @ncave could chime in about it.

**Comment by ncave** [comment]
@Shmew See if anything here helps: https://github.com/fable-compiler/Fable/issues/1981

**Comment by Shmew** [comment]
@gusty did ncave's link help?

**Comment by gusty** [comment]
Looks helpful, tbh I still have to study all the possibilities.
Do you have a specific suggestion?

**Comment by Shmew** [comment]
I have no idea which would be optimal to be honest, that's why I figured I'd leave the implementation to you 😅

**Comment by wallymathieu** [comment]
Well, perhaps we could pair program it?

**Comment by gusty** [comment]
@Shmew I read all the options but none of them seem to address our issue.

I did a forced cast for Fable, which in theory would throw exceptions but AFAIK the type checking process would prevent from comparing 2 different types.

Have a look at the PR #314

**Comment by Shmew** [comment]
Sorry I haven't been able to reply sooner! I've been pretty busy. It looks fine to me, if the tests pass then 👍.
