### ISSUE TITLE
Generic map and bind support for Nullable<_>

### ISSUE THREAD

**Issue by mattstermiller** [fsprojects/FSharpPlus#308]
### Description

There is currently no support for using the general functions and operators for map, bind, etc. on `System.Nullable<T>` like there is for `Option<T>`. This would be nice to have when using types from C#-style libraries.

**Comment by mattstermiller** [comment]
Is anyone opposed to adding this before I make a PR?

**Comment by wallymathieu** [comment]
There is an issue created by @gusty #191

**Comment by gusty** [comment]
@mattstermiller thanks, please comment in the linked issue the functions you plan to add and we can discuss it before adding the PR.

Note that some abstractions are not possible with Nullable, since they require changing the generic type and they are restricted to be value types, as opposed to options that have no restrictions.

**Comment by mattstermiller** [comment]
> There is an issue created by @gusty #191

I saw #191 but I interpreted that as a request for functions on a `Nullable` module. My request is specifically for Map, Bind, and other generic functions that already exist for `Option`.

For instance, I want to be able to write `Nullable 5 |>> ((*) 10) // should be (Nullable 50)`. Since these appear to be defined as overloads, I wouldn't think that adding an overload for Nullable to each would affect anything existing.

**Comment by mattstermiller** [comment]
For instance, the overload of Map for Option is here:
https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Control/Functor.fs#L61

So I'm proposing to add overloads for Nullable here and other generic functions that have an overload for Option. Although it does make sense to put the implementations in a Nullable module. Should I move this to #191?

**Comment by gusty** [comment]
Take for instance the generic `map` function, let's pretend it works with Nullables:

    open System

    let map f (x: Nullable<'t>) = if x.HasValue then Nullable (f x.Value) else Nullable ()

    let a = Nullable 5
    let b = map ((+) 2) a  // works

    let c = map string a // problem, string is not a value type

Now things get worst with applicatives. Here the whole abstraction becomes unusable as we need a lifted function and functions are not value types.

We could add an overload for map as a restricted one, as we did already with string which is not polymorphic.

To me it makes more sense as a separate module, but if you want you can create a PR containing the module functions (in the Extensions folder) and optionally an overload for Map and Bind which is restricted.

Then we can play with it, in principle I don't see a problem for the module functions, but for the overloads we'll need some testing.

We can keep both issues open for the moment.

**Comment by mattstermiller** [comment]
Thanks, I'll play with it and if it seems to work I'll submit a PR

**Comment by mattstermiller** [comment]
I created a PR with a Nullable module with map, bind and iter and overloads for the generic Map and Bind. Personally I wouldn't get much use out other things, but can add things like `exists` and `toList` if there would be a desire.
