### ISSUE TITLE
Math.Applicative operators lte and gte

### ISSUE THREAD

**Issue by MajorZiploc** [fsprojects/FSharpPlus#309]
Is it possible to add <= and >= to the Math.Applicative operators?

Example implementation being:

    let inline ( .<=  ) (x: '``Functor<'T>``)     (y: 'T)                   = map ((<=)/> y) x : '``Functor<bool>``
    let inline (  <=. ) (x: 'T)                   (y: '``Functor<'T>``)     = map ((<=)   x) y : '``Functor<bool>``
    let inline ( .<=. ) (x: '``Applicative<'T>``) (y: '``Applicative<'T>``) = (<=) <!> x <*> y : '``Applicative<bool>``

    let inline ( .>=  ) (x: '``Functor<'T>``)     (y: 'T)                   = map ((>=)/> y) x : '``Functor<bool>``
    let inline (  >=. ) (x: 'T)                   (y: '``Functor<'T>``)     = map ((>=)   x) y : '``Functor<bool>``
    let inline ( .>=. ) (x: '``Applicative<'T>``) (y: '``Applicative<'T>``) = (>=) <!> x <*> y : '``Applicative<bool>``

**Comment by gusty** [comment]
Yes, it shouldn't be a problem. If you want to add them please go ahead with a PR.

**Comment by gusty** [comment]
Closed by #310 
Thanks for the contribution !
