### ISSUE TITLE
Generic Concat function for Monoid

### ISSUE THREAD

**Issue by MajorZiploc** [fsprojects/FSharpPlus#319]
Would it be possible to add a generic concat function?
It would work similarly to Monoid.Sum
static member Sum (x:Seq<'Monoid>) :'Monoid

static member Concat (separator: 'Monoid) (x:Seq<'Monoid>) : 'Monoid

String.Concat from FSharp.Core is an example of this, but it is fixed to work for strings.

**Comment by gusty** [comment]
I think that function already exists, it is called `intercalate` and it works not just with `seq<'Monoid>` but with any foldable:

    /// Folds the source, inserting a separator between each element.
    intercalate (sep: 'Monoid) (source: '``Foldable<'Monoid>``)  : 'Monoid

`String.concat` is effectively a special case:

```
> String.concat "sep" ["a";"b";"c"] ;;
val it : string = "asepbsepc"

> intercalate "sep" ["a";"b";"c"] ;;
val it : string = "asepbsepc"
```

**Comment by gusty** [comment]
I think this request is satisfied with the above function, otherwise please re-open.
