### ISSUE TITLE
Include missing examples from f# meetup

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FSharpPlus#326]
### Description

A use of reader monad that could be included in the documentation was shown in: 
https://www.youtube.com/watch?v=pxJCHJgG8ws
by @starychfojtu

```f#
open System
open FSharpPlus
open FSharpPlus.Data

type IUserRepository =
    abstract GetUser : email : string -> string

type IShoppingListRepository =
    abstract Add : shoppingList : string list -> string list

let getUser email =
    Reader(fun (env : #IUserRepository) -> env.GetUser email)

let addShoppingList shoppingList =
    Reader(fun (env : #IShoppingListRepository) -> env.Add shoppingList)

type Env() =
    interface IUserRepository with
        member this.GetUser email =
                "Sandeep"    
    interface IShoppingListRepository with
            member this.Add shoppingList =
                shoppingList
```

**Comment by gusty** [comment]
I think yes, but it would be nice to add some explanation, otherwise a link to the explanation.

We need to include more sample code, but I hope this doesn't result in a doc which is a dump of code lacking explanations, as it was the sample folder since the beginning.

**Comment by wallymathieu** [comment]
Yes. Ideally also include a reasoning why you might want to use other patterns than the reader monad in this case.
