### ISSUE TITLE
NonEmptyMap

### ISSUE THREAD

**Issue by aammfe** [fsprojects/FSharpPlus#342]
Hello!!
Is there a NonEmptyMap like NonEmptyList?

**Comment by aammfe** [comment]
**Scenario:**
an Order has non empty Order lines and each Order line has unique Product.
current solution
```
type Order = {
Id:Id
OrderLines: Map<ProductId, OrderLine>
}
```
OR
```
type Order = {
Id:Id
OrderLines: ApprovedOrderLine NonEmptyList
}
```
in both cases just by looking at types I'm not confident that both of constraints will be apply.
but having NonEmptyMap will do the trick. 

**Proposal:**
NonEmptyMap will be just like Map but just like NonEmptyList it will have constructor with extra parameter a tuple which has 
(key,value) and an optional keyvalue tupple sequence.

 ```
type NonEmptyMap<'k,'v>(first:Tuple<'k, 'v> , rest:Tuple<'k, 'v> seq) = 
        new(first:Tuple<'k, 'v>) = NonEmptyMap(first, Seq.empty)
```

**Comment by gusty** [comment]
I think this could be a reasonable addition.
PR?

**Comment by cannorin** [comment]
Now I'm implementing this.
