### ISSUE TITLE
Monad computation does not work with TryWith as expected when used with Result

### ISSUE THREAD

**Issue by nikolamilekic** [fsprojects/FSharpPlus#346]
### Description

My logic here is that computation expressions should not deviate from universal concepts as that would surprise and confuse users. A `try...with` operation should always handle exceptions and not propagate them (in other words it should behave similarly to the `try...with` expression outside of a computation expression).

The `monad.strict` works as expected in this case, but `monad` does not.

### Repro steps

```fsharp

let r : Result<unit, Exception> = monad {
    try
        failwith "oops"
        return ()
    with exn -> return! Error exn
}

```

### Expected behavior

Error

### Actual behavior

Exception

**Comment by wallymathieu** [comment]
Seems unintentional.

**Comment by wallymathieu** [comment]
I think it's the same issue as #140, also visited in the issue #137

**Comment by nikolamilekic** [comment]
Oops, apologies, I didn't look through closed tickets and I missed #140 as that sounded like a general redesign instead of a specific fix. Would you like me to keep this open for the bug label, or close it in favor of #140?

**Comment by wallymathieu** [comment]
Well, I think close it in favor of #140 and talk write about your preference when it comes to how it should be done in that issue. Seems that it would make sense to have more explicit design.

**Comment by gusty** [comment]
Reopening the issue as I think it could be fixed independently without a whole redesign.

See #347 

If you try your code, you'll get a compilation error with a message explaining exactly what to do.
