### ISSUE TITLE
NonEmptySeq

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#354]
Given that we're going to add some NonEmpty collections, it will be natural to wish we had a NonEmptySeq that could be used as source for creating / transforming between them.

I think we can ensure non-emptiness  by using specific constructors:

 - We can create from a single value, alternatively taking an additional normal `seq` as "tail".
 - We can define a closed range operator that return a `NonEmptySeq` `|..`, also `..|` and `|..|` where the number besides the bar always exists in the range. Example `1|..3 -> NonEmptySeq [1;2;3]`, `1|..0 -> NonEmptySeq [1]`, `10|..|3 -> NonEmptySeq [3]`.
 - As in NonEmptyList, we can define a builder that doesn't allow the Zero method, for NonEmptySeq literals: `nes {1;2;3}`
 - Finally, we can add some safe/unsafe constructors from regular sequences, by checking on `Seq.isEmpty`

Any thoughs?

**Comment by wallymathieu** [comment]
In many instances we assume that the sequence has 1 as the step, though that's not always the case. Then there is the question about other types that has some sort of sequenceable or range behaviour?

**Comment by gusty** [comment]
What do you mean with 
> In many instances we assume that the sequence has 1

From the above list, only in the case of a unsafe construction we'll be assuming.

**Comment by wallymathieu** [comment]
The choice of using `|..`, `|..|`, `..|` looks like different inclusive/noninclusive ranges?

**Comment by gusty** [comment]
I hope so.
Not sure if there is a better operator symbol available for that. If so, please suggest.

**Comment by cannorin** [comment]
Should it look like this?

```fsharp
type NonEmptySeq<'T> =
  inherit IEnumerable<'T>
  abstract member Head: 'T
```

**Comment by gusty** [comment]
Yes, should we also add a `Tail` ?

**Comment by cannorin** [comment]
Yes, but the problem is that `NonEmptySet` and `NonEmptyMap` doesn't naturally have a tail.

**Comment by cannorin** [comment]
I mean, If the non-empty data type is built on top of a binary tree, it has two tails.

**Comment by gusty** [comment]
Good point, then we don't.

**Comment by cannorin** [comment]
Implementation started at #357.
