### ISSUE TITLE
Lens: Using items << filtered leads to "missing constraint" compile error without Intellisense error

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#359]
```f#
namespace Test

open FSharpPlus.Lens

type Child = { Id: string }

type Parent = { Children: Child list }

module Test =

  let inline _children f (p: Parent) =
    f p.Children <&> fun v -> { p with Children = v }

  let inline _child childId =
    _children << items << filtered (fun c -> c.Id = childId)
```

The above does not produce an Intellisense error, but compilation fails with the following error on `items` on the last line:

`error FS0193: A type parameter is missing a constraint 'when (FSharpPlus.Control.Traverse or Test.Child Microsoft.FSharp.Collections.list or  ^d) : (static member Traverse : Test.Child Microsoft.FSharp.Collections.list * (Test.Child ->  ^a) *  ^d * FSharpPlus.Control.Traverse ->  ^d)'`

I'm unable to get it to compile. What's wrong with the code? And shouldn't there be an Intellisense error, too?

**Comment by gusty** [comment]
I'm tagging this as an F# compiler error.
There is a PR in the F# compiler that will address it.
In the meantime we'll see if there's a workaround.

**Comment by gusty** [comment]
@cmeeren  Here's a quick workaround:

Since `items` is just an alias for `traverse`, you can replace it but using a specific traverse for your case.

So, for instance if you're working with `list` 

```
let inline _child childId =
    _children << List.traverse << filtered (fun c -> c.Id = childId)
```

**Comment by cmeeren** [comment]
Thanks! I didn't find an existing `List.traverse`, so I ended up doing this:

```f#
let inline _child childId =
    _children << (items: _ -> _ list -> _) << filtered (fun c -> c.Id = childId)
```

Feel free to close if you want.

**Comment by gusty** [comment]
Oh, that's also a good workaround.

Btw: I forgot to tell you, for `List.traverse` you need to open `FSharpPlus.Data` as it's an extension of `List`.

**Comment by cmeeren** [comment]
> you need to open `FSharpPlus.Data` as it's an extension of `List`.

Thanks, though based on your phrasing I'm having a hard time understanding how it being an extension of `List` means it should be under a namespace called `Data`. What's the rationale here?

**Comment by gusty** [comment]
Data provides additional types, but it also provides some generic extensions to existing types which I reckon it's a bit confusing since we have also extensions in Extensions.fs 

This is like this also for a technical reason, Extensions are used in Invokables, and Data uses Invokables, in this case to restrict to a less generic version.

We'll need to re-think this for V2.

CC @adz
