### ISSUE TITLE
Builders / type abbreviations for NonEmpty collections

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#363]
I propose we add a builder for `NonEmptySeq<_>` and type abbreviations for all 4 NonEmpty collections.

The question is, how do we call those builders / type abbreviations?

I can think of 2 options:
 

1. `neseq`, `nelist`, `nemap` and `neset`

2. `nseq`, `nlist`, `nmap` and `nset`

I think option 1 is being used in Haskell, with capital `NE`.

Anyway this is F# and although it's nice to align with other languages naming, we have different naming conventions.

Note: for the existing `nel` builder we can deprecate it, or just keep it as a second abbreviation, which won't be promoted.

Thoughts? Please, existing NonEmptyList users, chime in.

**Comment by baronfel** [comment]
Excellent idea! I prefer the`ne` prefix personally, `n` is a bit too open in terms of interpretations to me.

**Comment by adz** [comment]
I agree `ne` is better than `n` as prefix. `nelist` is a little more guessable than `nel`, so I like that.

Nice to complete the collections...

**Comment by cannorin** [comment]
I also prefer the `ne` prefix.

**Comment by SamuelBerger** [comment]
`ne` is indeed a more direct translation of NonEmpty and thus easier to guess / remember. n as in n times, nseq could be understood as n seq -> multiple sequences.

**Comment by gusty** [comment]
My vote goes for `n`.

So far it seems I'm the only one :(

**Comment by gusty** [comment]
Thanks for the feedback, `ne` is clearly the winner, with all voices (except mine) supporting it.
