### ISSUE TITLE
Change evaluation order for default <*> for functions?

### ISSUE THREAD

**Issue by ntwilson** [fsprojects/FSharpPlus#398]
### Description
Would you perhaps consider changing the order of evaluation in your default implementation of `<*>` for functions from this:
```F#
static member ``<*>`` (f: 'r -> _, g: _ -> 'T, [<Optional>]_output:  'r -> 'U, [<Optional>]_mthd: Apply) = 
  fun x -> f x (g x) : 'U
```
to something like this:
```F#
static member ``<*>`` (f: 'r -> _, g: _ -> 'T, [<Optional>]_output:  'r -> 'U, [<Optional>]_mthd: Apply) = 
  fun x -> let f' = f x in f' (g x) : 'U
```
?  When your Applicative context carries some sort of effect where order of evaluation can matter, I suspect most find it more intuitive that the effects are evaluated left to right.  A good example IMO of where this seems unintuitive would be:
```F#
> open FSharpPlus;;
> let fn =
-   let mutable x = 0
-   fun () ->
-     x <- x + 1
-     x;;
val fn : (unit -> int)

> (sequence [fn; fn; fn; fn] : unit -> int list) ();;
val it : int list = [4; 3; 2; 1]
```
I think it would be more intuitive if it came back as `[1; 2; 3; 4]`.  

### Known workarounds

Well, I mean you can build a SCU for a function, and give it a custom `<*>` definition.  I verified that if I build an SCU with custom definitions:
```F#
[<Struct>]
type IO<'a> = IO of (unit -> 'a) with
  // These static members allow FSharpPlus to recognize IO as Functor, Applicative, and Monad
  static member Map (IO fn, projection) = IO <| fun () -> projection (fn ())
  static member Return x = IO <| fun () -> x
  static member (<*>) (IO fn, IO x) = IO <| fun () -> 
    // careful trying to combine this, because we need to make sure `fn` is executed before `x`
    let fn' = fn () in fn' (x ())
  static member (>>=) (IO x, fn) = IO <| fun () -> let (IO io) = x () |> fn in io ()
```
Then it has the behavior I would expect.

### Related information 

* Operating system
* I'm using F#+ 1.1.1, but I'm pretty sure it's in master too (if I've tracked it down properly)
* net472

**Comment by gusty** [comment]
I think this proposal makes sense.
Although mixing side-effects with pure code is not a good idea, there might be some edge cases where this is justified or maybe not, but in anycase we can apply this change now, if there's no objections.

Do you want to submit a PR?

**Comment by ntwilson** [comment]
Sure, I'd love to.  Any particular thing you want tested with the change?  Should I test a case similar to the one above, like 
`Assert.AreEqual( (1,2,3), (tuple3 <!> fn <*> fn<*> fn) ())` 
or is that not a behavior you want to guarantee?  Should I add any particular regression tests?

**Comment by gusty** [comment]
Yes, I think those tests you propose would suffice. So we can guarantee the desired behavior.
