### ISSUE TITLE
FsCheck tests are not working

### ISSUE THREAD

**Issue by 3Rafal** [fsprojects/FSharpPlus#411]
Currently, all of FsCheck tests are false positive.
We use `Check.Quick` method to test properties, but it doesn't throw exception.
If a property fail, it will not be captured by test framework.

The simplest way to wire this properly is using `Check.QuickThrowOnFailure` as shown here:
https://fscheck.github.io/FsCheck/QuickStart.html#Integration-with-xUnit

**Comment by 3Rafal** [comment]
I have added a draft proposition (#412) of better FsCheck tests wiring. I've made it a draft, because proper tests fail for multiple cases.

**Comment by wallymathieu** [comment]
At least one of the failures look valid: "get tail from NonEmptyList". It doesn't look like the test make sense for collections of size 1.

**Comment by wallymathieu** [comment]
It also looks as if :
```f#
    let map2Shortest f l1 l2 = { Head = f l1.Head l2.Head; Tail = List.map2 f l1.Tail l2.Tail }
```
should actually be:
```f#
    let map2Shortest f l1 l2 = { Head = f l1.Head l2.Head; Tail = List.map2Shortest f l1.Tail l2.Tail }
```

**Comment by wallymathieu** [comment]
Thanks for the fix @3Rafal ! Thanks for the contribution! 👍
