### ISSUE TITLE
`<!>` operator not visible in docs

### ISSUE THREAD

**Issue by 3Rafal** [fsprojects/FSharpPlus#413]
In our operators docs we have `<!>` operator:  https://fsprojects.github.io/FSharpPlus/reference/fsharpplus-operators.html#(%20%3C!%3E%20)

It is not displayed properly, and we get `f x` instead of `f <!> x`.
![obraz](https://user-images.githubusercontent.com/22241847/102701660-98eb1d80-4259-11eb-890a-9f8d267ceeb9.png)

I've tested it both with Firefox and Chrome and it looks the same.
It seems that the reason for this, is that `<!>` gets treated as HTML comment, as pictured below:
![obraz](https://user-images.githubusercontent.com/22241847/102701717-1d3da080-425a-11eb-93a2-03288e730ccb.png)

**Comment by gusty** [comment]
Shouldn't we report this to FsDocs ?
Or is it a way to fix it from here?

**Comment by wallymathieu** [comment]
Looks like an FsDocs issue. Perhaps forgotten to markdown escape function names?

**Comment by wallymathieu** [comment]
Perhaps another thing we can do is have a remark in the doc text about the issue in order to make it less weird on the site.

**Comment by wallymathieu** [comment]
Could be https://github.com/fsprojects/FSharp.Formatting/pull/765/ I'll try to upgrade F# formatting and see if it fixes things
