### ISSUE TITLE
add function to Option similar to defaultArg but that receives a factory

### ISSUE THREAD

**Issue by leandromoh** [fsprojects/FSharpPlus#439]
Case we have an option and want to have a deafult value we can simply use `defaultArg` but the problem is that you must have the value already computed, which may not be desired if it is expensive computation.

Of course we can use pattern matching to have this laziness, but since already have functions for Option to improve experience, might be interesting to add one for this too

I think something like:

```fsharp
let orFallback  (fallback: unit -> 'T) (source: option<'T>) = 
  match source with 
  | Some x -> x 
  | None -> fallback()
```
use case
```fsharp

Some 3 |> Option.orFallback f  |> printfn "%d" 
None |> Option.orFallback f |> printfn "%d" 

```

I would like to open a PR for it, what do you think?

**Comment by adz** [comment]
I think this is already in F# core as Option.defaultWith. See https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/option.fs#L23-23

**Comment by leandromoh** [comment]
you are write @adz! I will close this issue

**Comment by adz** [comment]
No worries. I have found it hard to know what's in core and what's added by f#+, so understand!
