### ISSUE TITLE
Scan %o, %x and %X properly

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/FSharpPlus#440]
### Description

`%x` and `%X` scan like `%d`.

### Repro steps

```fs
#r "nuget:FSharpPlus"
FSharpPlus.Parsing.trySscanf "%X %x" "13 43"
```

### Expected behavior
`Some (19, 67)`

### Actual behavior

`Some (13, 43)`

### Known workarounds

None.

### Related information 

* Operating system: Windows
* Version: 1.1.7
* .NET Runtime, CoreCLR or Mono Version: F# Interactive version 11.4.2.0 for F# 5.0

**Comment by gusty** [comment]
See #442 for a repro for %o

**Comment by gusty** [comment]
Thanks for reporting this issue.

#443 is a tentative fix
