### ISSUE TITLE
Scan %o properly

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/FSharpPlus#442]
### Description

`%o` scans like `%d`.

### Repro steps

```fs
FSharpPlus.Parsing.trySscanf "%o" "10"
```

### Expected behavior

`Some 8`

### Actual behavior

`Some 10`

### Known workarounds

No

### Related information 

 -   Operating system: Windows
 -   Version: 1.1.7
 -   .NET Runtime, CoreCLR or Mono Version: F# Interactive version 11.4.2.0 for F# 5.0

**Comment by gusty** [comment]
Including this issue into #440
