### ISSUE TITLE
Abstractions graph won't show on Firefox properly

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/FSharpPlus#450]
### Description

![image](https://user-images.githubusercontent.com/19922066/120883900-7afc5400-c612-11eb-83b9-f7000ffce46d.png)

Directly accessing http://www.plantuml.com/plantuml/svg/f5PBRjim45s7f-0gy2UsWIuBsyYd2D25WG3kBiY2aYYPYKGg99N6JdooBdgaNg6KI56af2I0l1DdD3EFytd3Vt_-NWg9k2oo58WdGdF4KGR5I_A3P9WAmkXMxbCCOvGA381a2POxpE4RE4E1a1o54eOf4W9kSKOIpeeStj_lfCo_BnQno3bxnA4KyuJ8NH7C2LlSRdU8vtTf8HQr1nLb9chp-KvcwSD36G72AHnDn_0Lxi7P4NH2th2CKHGD2nXgurOu_Ae3l9heg_Lw30LCu7kfmZGg3wLkjT9_H4MUaX19N9eSWKBP0hbXb9616BFAje5O1ZnWpe2J6VXsbUSAc801apkeJSGHL13B_xRuUIwAJE5JuDheRWiQIiQ7mOkriOylGpcCLJ0Rlw07akledVfHTNn1d20gXrRHSU43qQeQJi_TLTwgqf4NF2muQXpueJcM1QTL4bITbXFLGrvAcXnDOKfY-QqygIRlfkWgbPZJKp0s3doCEClbtW1yxm2CIMa7--ks6JvrhPdh9ckzNfLj7VSdwv4Hsb_CQnAVqie1wMtcDqMEaeH7610D8p50OiA5jB04LiqMsJxh31bB8nIa0oiO6siNcSKrXPAf0Uyjaqh9IO43yaLe_SF6IKn7MMaE_Rfh53vfItYeqXWGorEjg_nICuwv67uNsJZuA8_w3-mKzRd0DCGVv5QU2YaWNuEo_pImL98yO9-iv3lEJXgAtDgtjgH563bZKMdIUbgh4xUdlksjbcR2-7uWyHlh5Z8b_XcPtRrSBajQyzQrufUr4VOjwolEsU-1H5kQ-koXH1MHLL-tXZ6IXjcKT5ipHwBfRpAPZ9lJ-VcvFbMiqhomu6pslgvV5g3UuLfgYR0bTxOTS3UVzOMY7hcpVu29Dv_R_rr9JNAUiA4WYwPoQrvklj0PSc0fiwDnMCtSrnaZxmO6mQTgrxCBtBst1Ua_MC38A2vy-LZZQeOFE7CuisqFHetumagDiMv4SAdUTUNB_3y0003__mC0 loads fine.

### Repro steps

Load http://fsprojects.github.io/FSharpPlus//abstractions.html on Firefox on Windows.

### Expected behavior

Graph loads properly.

### Actual behavior

Graph disappears.

### Known workarounds

Use Edge or Chrome.

### Related information 

* Operating system: Windows 10
* Branch: gh-pages
* .NET Runtime, CoreCLR or Mono Version: N/A
* Performance information, links to performance testing scripts: N/A

**Comment by Happypig375** [comment]
https://stackoverflow.com/a/28783110/5429648 doesn't fix this.

**Comment by Happypig375** [comment]
https://stackoverflow.com/a/58753349/5429648 seems to be helpful.

**Comment by adz** [comment]
@Happypig375 I found this happened because of uBlock firefox plugin. The image is on a different origin server, so get's blocked by default. I see the uBlock icon in your screenshot, so I'm guessing this happened to you too?

Can you check by allowing the block?

**Comment by wallymathieu** [comment]
@adz I've tried it on Firefox on one of my machines and tested with uBlock origin. It seems that it is working? Should we close this issue?

**Comment by adz** [comment]
I'd say so.
