### ISSUE TITLE
memoize fails if an argument to memoized function is illegal from F# compiler perspective

### ISSUE THREAD

**Issue by kentcb** [fsprojects/FSharpPlus#469]
## Description

If a memoized function takes an F# type as an argument, any value passed in _must_ be legal in order for memoization to work. Whilst this may sound desirable, we have a situation where we're trying to memoize union case values. If a union case value takes fields, the caller is not required to pass them in, so we "fill them in" by creating (and memoizing, but that's irrelevant) a default value. The default value may not be legal from F#'s perspective because there's only so much we can fill in. We then use that default value when calling another memoized function, and that's where the problem arises, because memoizing eventually invokes `GetHashCode` on the "illegal" object and that crashes with `NullReferenceException`.

### Repro steps

```fsharp
module Repro =
    open FSharpPlus
    open Xunit

    type SomeRecord = {
        Foo: List<string>
    }

    let getStuff (_: obj) : int * string =
        (42, "Answer to everything")

    let getStuffMemoized : (obj -> int * string) = memoizeN getStuff

    [<Fact>]
    let ``repro (crashes with System.NullReferenceException)`` () =
        let defaultRecordValue = {
            Foo = Unchecked.defaultof<List<string>>
        }
        getStuffMemoized defaultRecordValue |> ignore
```

### Expected behavior

Ideally, it would just treat any `null` values in the object structure as zero when calculating a hash. To be honest, I'm not sure that this is in FSharpPlus' hands because it's the `GetHashCode` generated by the F# compiler that is crashing. It assumes a valid object, presumably for performance reasons.

### Actual behavior

```
System.NullReferenceException : Object reference not set to an instance of an object.
  SomeRecord.GetHashCode(IEqualityComparer comp) line 0
  MemoizationKeyWrapper`1.GetHashCode(IEqualityComparer comp)
  MemoizationKeyWrapper`1.GetHashCode()
  ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
  MemoizeN.getOrAdd[a,b](ConcurrentDictionary`2 cd, FSharpFunc`2 f, a k)
  MemoizeN@28.Invoke(FSharpFunc`2 arg10, a arg20)
```

### Known workarounds

None that will work in a generic fashion (without the caller having to do some custom mangling of their types).

**Comment by gusty** [comment]
I think the problem here is that ConcurrentDictionary calls the hash function on the object, then the object calls internally its hash function, which assumes non-nullable values and therefore it fails.

Here's a small repro:

```
type A = A
type SomeRecord = {    Foo: A }
let defaultRecordValue = { Foo = Unchecked.defaultof<A> }
hash defaultRecordValue
```

I can't think of any reasonable workaround, the best we can do is suggest that the F# compiler generate null checks for the hashing function of types that are "supposed" not to be null.

**Comment by kentcb** [comment]
Yeah, I agree, and as mentioned I think that will be for performance reasons and too drastic a change to the F# compiler for my little ol' use case.

That said, I've been thinking more about my use case and feel like I want to memoize based on the _type_ of the dummy value rather than the value itself. After all, it's just a stand-in value not provided by the caller - the caller provides the type. I believe I could write a wrapper type that includes both the type and dummy value, but hashes based only on the type. Will try that.

**Comment by kentcb** [comment]
Definitely not the first time this issue has come up: https://github.com/dotnet/fsharp/issues/1044

**Comment by kentcb** [comment]
Ended up getting around this by defining my own record type with custom equality. The record encapsulates the two fields I was originally memoizing on, but overrides `GetHashCode` + `Equals` so that only the relevant field is used. By memoizing a function taking this custom record as a parameter, it memoizes how I want.

**Comment by gusty** [comment]
For the record, here is the original suggestion to fix this https://github.com/fsharp/fslang-suggestions/issues/92
