### ISSUE TITLE
Reader monad transform one env to another

### ISSUE THREAD

**Issue by padzikm** [fsprojects/FSharpPlus#471]
### Description

Hi, I' d like to chain two reader monads, where one env is subtype of the other, so inner function can access only type it requires and outer function can requires general env param.

### Repro steps

```
type Env = {Now: DateTime; Conn: string}

type InnerEnv = {Now: DateTime}

let inner () =
    monad {
        let! (e:InnerEnv) = Reader.ask
        return doWork e.Now
    }

let outer () =
    monad {
        let! (e:Env) = Reader.ask
        let! m = Reader (fun p -> {Now = p.Now})
        let! r = inner()
        let! m = Reader.local (fun (x:Env) -> {Now = x.Now})
        return r
    }
```

### Expected behavior

Expected result is function outer with signature Reader<Env, Result>

### Actual behavior

Doesn't compile

**Comment by padzikm** [comment]
I found solution:
```
type Env = {Now: DateTime; Conn: string}

type InnerEnv = {Now: DateTime}

let inner () =
    monad {
        let! (e:InnerEnv) = Reader.ask
        return doWork e.Now
    }

let outer () =
    monad {
        let! r1 = inner() |> Reader.local (fun (x:Env) -> {Now = x.Now})
        let! r 2= otherInner() |> Reader.local (fun (x:Env) -> {Conn = x.Conn})
        return r1, r2
    }
```

**Comment by wallymathieu** [comment]
That's neat. Is this something you think should be documented? @padzikm

**Comment by padzikm** [comment]
@wallymathieu thanks, I miss examples such above in tests. I'm writing purely functional app in my free time and often looking for non trivial usage of functional concepts in f# and f#+ - it's very helpful to see nontrivial examples in tests

**Comment by gusty** [comment]
@padzikm I don't think you can do that without using some SRTP accessor functions.

However you said you managed to make it work, still the code you posted doesn't compile, first because you are missing nuget, open namespaces and some functions, but I tried to fill the holes and still doesn't work:

```FSharp
#r "nuget: FSharpPlus"

open System
open FSharpPlus
open FSharpPlus.Data

type Env = {Now: DateTime; Conn: string}

type InnerEnv = {Now: DateTime}


let doWork x = x

let inner () =
    monad {
        let! (e:InnerEnv) = Reader.ask
        return doWork e.Now
    }

let otherInner () =
    monad {
        let! (e:InnerEnv) = Reader.ask
        return doWork e.Now
    }


let outer () =
    monad {
        let! r1 = inner() |> Reader.local (fun (x:Env) -> {Now = x.Now})
        let! r2 = otherInner() |> Reader.local (fun (x:Env) -> {Conn = x.Conn})
        return r1, r2
    }
```

The error here is `~vsC456.fsx(30,65): error FS1129: The record type 'InnerEnv' does not contain a label 'Conn'.`

Could you possibly post a full repro?

**Comment by padzikm** [comment]
@gusty I wrote this as a shortened example, thanks for filling holes - one small detail from your code will make it work I think:
```
#r "nuget: FSharpPlus"

open System
open FSharpPlus
open FSharpPlus.Data

type Env = {Now: DateTime; Conn: string}

type InnerEnv = {Now: DateTime}


let doWork x = x

let inner () =
    monad {
        let! (e:InnerEnv) = Reader.ask
        return doWork e.Now
    }

let otherInner () =
    monad {
        let! (e:InnerEnv) = Reader.ask
        return doWork e.Now
    }


let outer () =
    monad {
        let! r1 = inner() |> Reader.local (fun (x:Env) -> {Now = x.Now})
        let! r2 = otherInner() |> Reader.local (fun (x:Env) -> {Conn = x.Conn})
        return r1, r2
    }
```

btw what is srtp accessor function?

**Comment by gusty** [comment]
I see, it looks like I misunderstood your problem.

I was thinking in having a generic env with some constraints, and I came up once with a solution which requires SRTP accessor functions for each property, which is something like:

`let inline getConn x =  (^T : (member Conn : _) x)`

but as I said, this is not what you need.
