### ISSUE TITLE
The link to Result does not work.

### ISSUE THREAD

**Issue by KPMTGG** [fsprojects/FSharpPlus#473]
The link to [Result](https://docs.microsoft.com/dotnet/api/microsoft.fsharp.core.fsharpresult-2) does not work.

**Comment by wallymathieu** [comment]
Does the documentation link on the F#+ documentation site work now @KPMTGG ? We have recently upgraded the documentation tool.

**Comment by gusty** [comment]
I think if no one can point to this error we should close this issue.
