### ISSUE TITLE
`String.take 0 s` throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by rzikm** [fsprojects/FSharpPlus#531]
### Description

calling `String.take` with count = 0 throws IndexOutOfRangeException

### Repro steps

```fsharp
module Program

[<EntryPoint>]
let main args =
    FSharpPlus.String.take 0 "awfew" |> String.length
```

### Expected behavior

`String.take 0 s` returns empty string

### Actual behavior

IndexOutOfRangeException

### Known workarounds

Use String.truncate

### Related information 

Library version: 1.2.5

**Comment by gusty** [comment]
I'm failing to reproduce this.

@wallymathieu does it works for you?

@rzikm can you tell me exactly which F#+ version are using?

**Comment by rzikm** [comment]
I was using 1.2.5, but the error goes away when I upgrade.
