### ISSUE TITLE
[API Proposal] String.(try)FindLastSliceIndex

### ISSUE THREAD

**Issue by rzikm** [fsprojects/FSharpPlus#574]
We have String.{try}FindSliceIndex as an alternative to C# String.IndexOf(string), I could use also the equivalent of String.LastIndexOf(string).

```fs
module String;

    let findLastSliceIndex (slice: string) (source: string) =
        let index = source.LastIndexOf slice
        if index = -1 then
            ArgumentException("The specified substring was not found in the string.") |> raise
        else
            index
            
    let tryFindLastSliceIndex (slice: string) (source: string) =
        let index = source.LastIndexOf slice
        if index = -1 then None else Some index
```

I can put up a PR if approved.

**Comment by wallymathieu** [comment]
Looks interesting. How would the code that uses that compare to code that uses the string methods look?

**Comment by gusty** [comment]
This looks interesting. specially if it could also be generalized to other collections.

Feel free to submit a PR, either just for strings or for all collections (see for instance the function `replace`)
