### ISSUE TITLE
{ Homepage } Overlapping diagram

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/FSharpPlus#75]
See here: https://gusty.github.io/FSharpPlus/abstractions.html
![screenshot_20180116_130016](https://user-images.githubusercontent.com/6344099/34987978-63fdc4e2-fabd-11e7-972b-771bc04a4b8a.png)

This happens on a 1366x768

**Comment by ShalokShalom** [comment]
Oh, I love it right. Left is where we start to read since that are our eyes easier there. Which means it catches our attention all the time. I cant focus on the content anymore then.

**Comment by gusty** [comment]
Worst case we change it to the left until a better solution is implemented.

**Comment by wallymathieu** [comment]
I talked to a [coworker](@vnorr) way better at CSS than me. He recommended using flexbox instead.

**Comment by gusty** [comment]
After a quick search I found this: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

So, now we need someone familiar with flexbox :)
