### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/FSharpPlus#88]
Hi there :slightly_smiling_face: 

[This](https://www.youtube.com/watch?v=fNH0Ql8_Zmo) looks very useful. ^-^

**Comment by gusty** [comment]
We'll need to create a ``FSharpPlus.NiceHacks`` namespace ;)

**Comment by ShalokShalom** [comment]
How do we do that?

**Comment by gusty** [comment]
First we'll need some discussion.

Try to answer, what are the use cases, which different implementations are being evaluated and what is the impact of choosing one over the other.

Feel free to add some more context !

**Comment by ShalokShalom** [comment]
One over the other? Is there any different implementation as yours?

I simply think the initially linked video is reason enough?

Which are the potential downsides, that you encounter? :slightly_smiling_face:

**Comment by wallymathieu** [comment]
By using concurrent dictionary you imply that you will use it in a certain way. You might want to memoize in other ways. Say for instance that the computation is expensive enough to warrant saving the result into a database. If you know that you wont need concurrent usage, then you can probably get some performance improvement by using a regular dictionary.

**Comment by ShalokShalom** [comment]
So different ways of memoization or one other implementation for all?

**Comment by gusty** [comment]
Unless we agree in a reasonable default.

**Comment by wallymathieu** [comment]
What defaults does for `Lazy<>` does `let identifier = lazy ( expression )` translate to?

**Comment by gusty** [comment]
I think it's equivalent to ``let identifier = Lazy(fun () -> expression)``.

**Comment by gusty** [comment]
So, do you think the concurrent one could be a reasonable default?

**Comment by wallymathieu** [comment]
https://stackoverflow.com/questions/15252115/concurrentdictionary-performance-at-a-single-thread-misunderstanding

**Comment by wallymathieu** [comment]
If the difference is only a small factor (4), so having concurrent as the default should be OK.

**Comment by gusty** [comment]
Yes, I was thinking that it might be good to use safer one as default. Since you need to have certain guarantees.

**Comment by gusty** [comment]
Now the question is whether we define a set of functions for different arities or do we use something like the polyvariadic version, which automatically infers the arity from the context.

**Comment by ShalokShalom** [comment]
Which are the pros on these two sides?

**Comment by gusty** [comment]
Advantages of many functions: better type inference in situations when the function argument is not known (ie: when passed as argument to another function). Possible optimizations for arities > 1.

Advantages of a single polyvariadic function: we have potentially infinite implementations (yesterday I found at work a function with 45 parameters) on a single function.

I would like to add this function together with other utility functions like this one (feel free to add to the list), we can start working on a branch once we decide which way to go but I wouldn't merge this branch before v1.0 to avoid possible additional unwanted dependencies.

**Comment by gusty** [comment]
Yes, we should start using more feature branches for stuff like this.

**Comment by ShalokShalom** [comment]
Type inference always sounds nice, how many different implementations are possible to integrate and is this enough in your perspective? :)

**Comment by gusty** [comment]
I think if we go that road we should implement ``memoize``, ``memoize2`` and ``memoize3``.

**Comment by ShalokShalom** [comment]
Oh, optimizations to the type inference sounds nice, how many implementations are possible with this approach and do you consider this as enough? :smile:

**Comment by ShalokShalom** [comment]
Sorry, I hit the delete button accidentally, so I wrote this text again. :)

**Comment by gusty** [comment]
Ok, I will do the same. To have the right order. Afterward I will delete this message.

**Comment by gusty** [comment]
I think if we go that road we should implement ``memoize``, ``memoize2`` and ``memoize3``.

**Comment by voronoipotato** [comment]
would it be useful to take a list of parameters?

**Comment by wallymathieu** [comment]
Having a similar structure for the memoize methods and having a default with concurrent dictionary implemented memoize and a secondary implementation in a different module/namespace with regular dictionary (since a factor of 4 even if small could be something that someone does really care about if in a very tight loop).

**Comment by cmeeren** [comment]
Is there any reason this stagnated? Memoization would be great to see in FSharpPlus! 😊 The polyvariadic alternative seems useful, but I haven't tried it myself and can't speak to potential downfalls.

**Comment by gusty** [comment]
No, there's no particular reason why.
I just wonder if it's the right place to have it in the main namespace. I think it is.
I can create a PR and then we try it and discuss it.

**Comment by wallymathieu** [comment]
Yes, having a module for it would make more sense.

**Comment by cmeeren** [comment]
Does it also make sense to not have it in the main namespace if it's just the one polyvariadic function called `memoize`? (Assuming that's the alternative that will be implemented.)

**Comment by gusty** [comment]
Yes, that's exactly what I'm worried of. Having a single namespace, with a single function doesn't make much sense.

I propose we put it in the main namespace for now. We can always deprecate later some functions there and advise to open a specific one.

**Comment by gusty** [comment]
@cmeeren if you want to submit a PR, please go ahead !
