### ISSUE TITLE
Operator documentation 

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/FSharpPlus#91]
I stumbled now around half an hour through the docsrc/content folder and I miss the following .fsx files:

https://gusty.github.io/FSharpPlus/reference/fsharpplus-operators.html

And all its subfiles, such as: https://gusty.github.io/FSharpPlus/reference/fsharpplus-operators-seq.html

Any idea, where they are?

**Comment by gusty** [comment]
I just realized some days ago that there is a mess in the docs, because it doesn't delete the old docs.
So old docs are still there, although not linked anymore form the home.
I think the solution is as easy as drop the gh-pages branch and create it again from scratch.

**Comment by gusty** [comment]
I did a doc cleanup. Those files don't make noise anymore.

**Comment by wallymathieu** [comment]
Nice 😄

**Comment by ShalokShalom** [comment]
Thanks ^-^
